name: CICD DEVOPSREST

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: killer86
          password: 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

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/devopsrest2024-2025:latest .

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'  # Only push on main branch
        run: |
          docker push ghcr.io/${{ github.repository }}/devopsrest2024-2025